version: "3.9"

services:
  discovery:
    image: consul:1.9
    ports:
      - 8500:8500

  gateway:
    image: demo-microservices/gateway
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery 
        -DCONSUL_PORT=8500
    depends_on:
      - discovery

  auth:
    image: demo-microservices/service-auth
    restart: always
    ports:
      - 8081:8081
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery 
        -DCONSUL_PORT=8500
    depends_on:
      - discovery

  parties:
    image: demo-microservices/service-jeu
    restart: always
    ports:
      - 8082:8082
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery 
        -DCONSUL_PORT=8500
    depends_on:
      - discovery