# @no-cookie-jar
POST http://localhost:8081/authent/inscription
Content-Type: application/json

{"email":"n.saiah@etu.univ-orleans.fr", "login":"nadir", "password":"mdp123"}

> {%
    client.global.set("token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###



GET http://localhost:8081/authent/inscription/nadir
Authorization: {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

DELETE http://localhost:8081/authent/inscription/nadir
Authorization: {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}


###

GET http://localhost:8081/authent/inscription/nadir
Authorization: {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}