# @no-cookie-jar
POST http://localhost:8080/api/auth/inscription
Content-Type: application/json

{"email":"n.saiah@etu.univ-orleans.fr", "login":"nadir", "password":"mdp123"}

> {%
    client.global.set("token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
